package sk.zvjs.holup.accommodation.convert;

import com.fasterxml.jackson.annotation.*;

@lombok.Data
public class Attributes {
    @lombok.Getter(onMethod_ = {@JsonProperty("FID")})
    @lombok.Setter(onMethod_ = {@JsonProperty("FID")})
    private long fid;
    @lombok.Getter(onMethod_ = {@JsonProperty("N\u00e1zov_pos")})
    @lombok.Setter(onMethod_ = {@JsonProperty("N\u00e1zov_pos")})
    private String nzovPos;
    @lombok.Getter(onMethod_ = {@JsonProperty("Adresa_s\u00ed")})
    @lombok.Setter(onMethod_ = {@JsonProperty("Adresa_s\u00ed")})
    private String adresaS;
    @lombok.Getter(onMethod_ = {@JsonProperty("Telefonick")})
    @lombok.Setter(onMethod_ = {@JsonProperty("Telefonick")})
    private String telefonick;
    @lombok.Getter(onMethod_ = {@JsonProperty("E_mail")})
    @lombok.Setter(onMethod_ = {@JsonProperty("E_mail")})
    private String eMail;
    @lombok.Getter(onMethod_ = {@JsonProperty("\u0160tatut\u00e1r")})
    @lombok.Setter(onMethod_ = {@JsonProperty("\u0160tatut\u00e1r")})
    private String tatutr;
    @lombok.Getter(onMethod_ = {@JsonProperty("Webov\u00e1_lo")})
    @lombok.Setter(onMethod_ = {@JsonProperty("Webov\u00e1_lo")})
    private String webovLo;
    @lombok.Getter(onMethod_ = {@JsonProperty("Pohlavie")})
    @lombok.Setter(onMethod_ = {@JsonProperty("Pohlavie")})
    private String pohlavie;
    @lombok.Getter(onMethod_ = {@JsonProperty("Vek")})
    @lombok.Setter(onMethod_ = {@JsonProperty("Vek")})
    private String vek;
    @lombok.Getter(onMethod_ = {@JsonProperty("Trval\u00fd_pr")})
    @lombok.Setter(onMethod_ = {@JsonProperty("Trval\u00fd_pr")})
    private String trvalPR;
    @lombok.Getter(onMethod_ = {@JsonProperty("Poskytovan")})
    @lombok.Setter(onMethod_ = {@JsonProperty("Poskytovan")})
    private Poskytovan poskytovan;
    @lombok.Getter(onMethod_ = {@JsonProperty("Typ_slu\u017eb")})
    @lombok.Setter(onMethod_ = {@JsonProperty("Typ_slu\u017eb")})
    private String typSlub;
    @lombok.Getter(onMethod_ = {@JsonProperty("Adresa_zar")})
    @lombok.Setter(onMethod_ = {@JsonProperty("Adresa_zar")})
    private String adresaZar;
    @lombok.Getter(onMethod_ = {@JsonProperty("Celkov\u00e1_u")})
    @lombok.Setter(onMethod_ = {@JsonProperty("Celkov\u00e1_u")})
    private String celkovU;
    @lombok.Getter(onMethod_ = {@JsonProperty("Aktu\u00e1lne_")})
    @lombok.Setter(onMethod_ = {@JsonProperty("Aktu\u00e1lne_")})
    private long aktulne;
    @lombok.Getter(onMethod_ = {@JsonProperty("Telef\u00f3nne")})
    @lombok.Setter(onMethod_ = {@JsonProperty("Telef\u00f3nne")})
    private String telefnne;
    @lombok.Getter(onMethod_ = {@JsonProperty("Maxim\u00e1lna")})
    @lombok.Setter(onMethod_ = {@JsonProperty("Maxim\u00e1lna")})
    private long maximlna;
    @lombok.Getter(onMethod_ = {@JsonProperty("V\u00fd\u0161ka_\u00fa")})
    @lombok.Setter(onMethod_ = {@JsonProperty("V\u00fd\u0161ka_\u00fa")})
    private String vka;
    @lombok.Getter(onMethod_ = {@JsonProperty("\u010eal\u0161ie_s")})
    @lombok.Setter(onMethod_ = {@JsonProperty("\u010eal\u0161ie_s")})
    private String alieS;
    @lombok.Getter(onMethod_ = {@JsonProperty("Sp\u00f4sob_pr")})
    @lombok.Setter(onMethod_ = {@JsonProperty("Sp\u00f4sob_pr")})
    private String spsobPR;
    @lombok.Getter(onMethod_ = {@JsonProperty("Mo\u017enos\u0165_")})
    @lombok.Setter(onMethod_ = {@JsonProperty("Mo\u017enos\u0165_")})
    private String monos;
    @lombok.Getter(onMethod_ = {@JsonProperty("Existencia")})
    @lombok.Setter(onMethod_ = {@JsonProperty("Existencia")})
    private String existencia;
    @lombok.Getter(onMethod_ = {@JsonProperty("GPS")})
    @lombok.Setter(onMethod_ = {@JsonProperty("GPS")})
    private String gps;
    @lombok.Getter(onMethod_ = {@JsonProperty("N\u00e1zov_zar")})
    @lombok.Setter(onMethod_ = {@JsonProperty("N\u00e1zov_zar")})
    private String nzovZar;
    @lombok.Getter(onMethod_ = {@JsonProperty("Zodpovedn")})
    @lombok.Setter(onMethod_ = {@JsonProperty("Zodpovedn")})
    private String zodpovedn;
    @lombok.Getter(onMethod_ = {@JsonProperty("fotografia")})
    @lombok.Setter(onMethod_ = {@JsonProperty("fotografia")})
    private String fotografia;
    @lombok.Getter(onMethod_ = {@JsonProperty("Lat")})
    @lombok.Setter(onMethod_ = {@JsonProperty("Lat")})
    private double lat;
    @lombok.Getter(onMethod_ = {@JsonProperty("Lon")})
    @lombok.Setter(onMethod_ = {@JsonProperty("Lon")})
    private double lon;
    @lombok.Getter(onMethod_ = {@JsonProperty("Aktualizovan\u00e9")})
    @lombok.Setter(onMethod_ = {@JsonProperty("Aktualizovan\u00e9")})
    private Long aktualizovan;
    @lombok.Getter(onMethod_ = {@JsonProperty("Kraj")})
    @lombok.Setter(onMethod_ = {@JsonProperty("Kraj")})
    private String kraj;
}